<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD'=>'הוסף משתמש',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES'  =>  'ההעדפות שלי',
	'LBL_MORE_INFORMATION'  =>  'מידע נוסף',
	'LBL_USERLOGIN_ROLE'  =>  'משתמש כניסהותפקיד',
	'LBL_USER_IMAGE_INFORMATION'=>'תמונת משתמש',
	'LBL_CURRENCY_CONFIGURATION'=>'מטבעומספר שדה תצורה',
	'LBL_ADDRESS_INFORMATION'=>'כתובת משתמש',
	'LBL_USER_ADV_OPTIONS'=>'משתמש אפשרויות מתקדמות',
	'תצורת אסטריסק'  =>  'Asterisk Configuration',
	'LBL_HOME_PAGE_COMPONENTS'=>'דף בית רכיבים',
	'LBL_TAG_CLOUD_DISPLAY'=>'הצגת תג קלאוד',

	//MyPreference Fields
	'Role'=>'תפקיד',
	'Admin'=>'Admin',
	'User Name'=>'שם משתמש',
	'Default Activity View'=>'צפו בלוח השנה ברירת מחדל',
	'Default Lead View'=>'צפה בעופרת ברירת מחדל',
	'Title'=>'כותרת',
	'Office Phone'=>'טלפון של משרד',
	'Department'=>'מחלקה',
	'Reports To'=>'דוחות כדי',
	'Yahoo id'=>'id yahoo',
	'Home Phone'=>'טלפון בבית',
	'User Image'=>'העלה תמונה',
	'Date Format'=>'פורמט תאריך',
	'Tag Cloud'=>'תג קלאוד',
	'Signature'=>'חתימה',
	'Street Address'=>'כתובת רחוב',
	'Password'=>'סיסמא',
	'Confirm Password'=>'אשר סיסמא',
	'LBL_SHOWN'=>'מוצג',
	'LBL_HIDDEN'=>'חבוי',
	'LBL_SHOW'=>'הצגה',
	'LBL_HIDE'=>'להסתיר',
	'LBL_HOME_PAGE_COMPO'=>'דף בית רכיבים',
	'LBL_LOGIN_HISTORY'=>'התחברות היסטוריה',
	'LBL_USERDETAIL_INFO'=>'צופה בפרטי משתמש',
	'LBL_DELETE_GROUP'=>'מחיקת הקבוצה',
	'LBL_DELETE_GROUPNAME'=>'הקבוצהשנמחקה',
	'LBL_TRANSFER_GROUP'=>'העברת בעלותל:',
	'LBL_DELETE_USER'=>'משתמששנמחק',
	'LBL_TRANSFER_USER'=>'העברת בעלותלמשתמש',
	'LBL_DELETE_PROFILE'=>'מחיקת פרופיל',
	'LBL_TRANSFER_ROLES_TO_PROFILE'=>'להעביר תפקידים לפרופיל',
	'LBL_PROFILE_TO_BE_DELETED'=>'פרופילשנמחק',
	'INTERNAL_MAIL_COMPOSER'=>'מלחין דואר פנימי',
	'הארכת אסטריסק'  =>  'Asterisk Extension',
	' לקבל שיחות נכנסות'  =>  'Receive Incoming Calls',
	'Webservice Access Key'=>'מפתח גישה',
	'Language'=>'שפה',
	'Theme'=>'נושא',
	'אזור הזמן'  =>  'Time Zone',
	'מפריד עשרוני'  =>  'Decimal Separator',
	'תבנית קיבוץ ספרות'  =>  'Digit Grouping Pattern',
	'ספרות קיבוץ מפריד'  =>  'Digit Grouping Separator',
	'מיקום סמל'  =>  'Symbol Placement',
	'מספר השברים העשרוני מטבע'  =>  'Number Of Currency Decimals',
	'לחתוך נגרר אפסים'  =>   'Truncate Trailing Zeros',
	'Default Call Duration'=>'משך שיחת ברירת מחדל ( דקות )',
	'Other Event Duration'=>'משך אירוע אחר ( דקות )',
	'Calendar Hour Format'=>'פורמט שעת לוח השנה',
	'Tag Cloud'=>'תג קלאוד',

	//Time zones-Dont change any value
    'Kwajalein'  =>  '(UTC -12 : 00) קו תאריך הבינלאומי המערבי',
    'Pacific/Midway'  =>  '(UTC -11 : 00) זמן אוניברסלי מתואם -11',
    'Pacific/Samoa'  =>  '(UTC -11 : 00) סמואה',
    'Pacific/Honolulu'  =>  '(UTC -10 : 00) הוואי',
    'America/Anchorage'  =>  '(UTC -09 : 00) אלסקה',
    'America/Los_Angeles'  =>  '(UTC -08 : 00) שעון החוף המערבי (ארה"ב וקנדה )',
    'America/Tijuana'  =>  '(UTC -08 : 00) טיחואנה, באחה קליפורניה',
    'America/Denver'  =>  '(UTC -07 : 00) זמן הרים (ארה"ב וקנדה )',
    'America/Chihuahua'  =>  '(UTC -07 : 00) ציוואווה, לה פאס , מזטלן',
    'America/Mazatlan'  =>  '(UTC -07 : 00) מזטלן',
    'America/Phoenix'  =>  '(UTC -07 : 00) אריזונה',
    'America/Regina'  =>  '(UTC -06 : 00) Saskatchewan',
    'America/Tegucigalpa'  =>  '(UTC -06 : 00) המרכז אמריקה',
    'America/Chicago'  =>  '(UTC -06 : 00) זמן מרכז (ארה"ב וקנדה )',
    'America/Mexico_City'  =>  '(UTC -06 : 00) מקסיקו סיטי',
    'America/Monterrey'  =>  '(UTC -06 : 00) מונטריי',
    'America/New_York'  =>  '(UTC -05 : 00) שעון החוף מזרחי (ארה"ב וקנדה )',
    'America/Bogota'  =>  '(UTC -05 : 00) בוגוטה , לימה, קיטו',
    'America/Lima'  =>  '(UTC -05 : 00) לימה',
    'America/Rio_Branco'  =>  '(UTC -05 : 00) ריו ברנקו',
    'America/Indiana/Indianapolis'  =>  '(UTC -05 : 00) אינדיאנה (מזרח)',
    'America/Caracas'  =>  '(UTC -04 : 30 ) קראקס',
    'America/Halifax'  =>  '(UTC -04: 00 ) שעון אוקיינוס ​​האטלנטי (קנדה )',
    'America/Manaus'  =>  '(UTC -04: 00 ) מנאוס',
    'America/Santiago'  =>  '(UTC -04: 00 ) סנטיאגו',
    'America/La_Paz'  =>  '(UTC -04: 00 ) לה פאס',
    'America/Cuiaba'  =>  '(UTC -04: 00 ) קויאבה',
    'America/Asuncion'  =>  '(UTC -04: 00 ) אסונסיון',
    'America/St_Johns'  =>  '(UTC -03 : 30 ) ניופאונדלנד',
    'America/Argentina/Buenos_Aires'  =>  '(UTC -03 : 00) בואנוס איירס',
    'America/Sao_Paulo'  =>  '(UTC -03 : 00) ברזיליה',
    'America/Godthab'  =>  '(UTC -03 : 00) גרינלנד',
    'America/Montevideo'  =>  '(UTC -03 : 00) מונטווידאו',
    'Atlantic/South_Georgia'  =>  '(UTC -02 : 00) אמצע האטלנטי',
    'Atlantic/Azores'  =>  '(UTC - 01: 00) איים האזוריים',
    'Atlantic/Cape_Verde'  =>  '(UTC - 01: 00) קייפ ורדה האם .',
    'Europe/London'  =>  '(UTC ) בלונדון , אדינבורו, דבלין , ליסבון',
    'UTC'  =>  '(UTC ) זמן אוניברסלי מתואם , השעון גריניץ',
    'Africa/Monrovia'  =>  '(UTC ) מונרוביה, רייקיאוויק',
    'Africa/Casablanca'  =>  '(UTC ) קזבלנקה',
    'Europe/Belgrade'  =>  '(UTC +01:00) בלגרד , ברטיסלבה , בודפשט, לובליאנה , פראג',
    'Europe/Sarajevo'  =>  '(UTC +01:00) סרייבו , סקופיה , ורשה, זאגרב',
    'Europe/Brussels'  =>  '(UTC +01:00) בריסל , קופנהגן , מדריד, פריז',
    'Africa/Algiers'  =>  '(UTC +01:00) מערב מרכז אפריקה',
    'Europe/Amsterdam'  =>  '(UTC +01:00) אמסטרדם , ברלין , ברן , רומא , שטוקהולם, וינה',
    'Europe/Minsk'  =>  '(UTC +02:00) מינסק',
    'Africa/Cairo'  =>  '(UTC +02:00) קהיר',
    'Europe/Helsinki'  =>  '(UTC +02:00) הלסינקי , ריגה, סופיה, טאלין , וילנה',
    'Europe/Athens'  =>  '(UTC +02:00) אתונה, בוקרשט',
    'Europe/Istanbul'  =>  '(UTC +02:00) איסטנבול',
    'Asia/Jerusalem'  =>  '(UTC +02:00) ירושלים',
    'Asia/Amman'  =>  '(UTC +02:00) עמאן',
    'Asia/Beirut'  =>  '(UTC +02:00) ביירות',
    'Africa/Windhoek'  =>  '(UTC +02:00) וינדהוק',
    'Africa/Harare'  =>  '(UTC +02:00) הרארה',
    'Asia/Kuwait'  =>  '(UTC +03:00) כווית, ריאד',
    'Asia/Baghdad'  =>  '(UTC +03:00) בגדד',
    'Africa/Nairobi'  =>  '(UTC +03:00) ניירובי',
    'Asia/Tehran'  =>  '(UTC +03:30) טהרן',
    'Asia/Tbilisi'  =>  '(UTC +04:00) טביליסי',
    'Europe/Moscow'  =>  '(UTC +04:00) מוסקווה, וולגוגרד',
    'Asia/Muscat'  =>  '(UTC +04:00) אבו דאבי , מוסקט',
    'Asia/Baku'  =>  '(UTC +04:00) באקו',
    'Asia/Yerevan'  =>  '(UTC +04:00) ירוואן',
    'Asia/Karachi'  =>  '(UTC +05:00) איסלמאבאד , קראצי',
    'Asia/Tashkent'  =>  '(UTC +05:00) טשקנט',
    'Asia/Kolkata'  =>  '(UTC +05:30) נאי , כלכותה, מומבאי , ניו דלהי',
    'Asia/Colombo'  =>  '(UTC +05:30) סרי גאווארדנפורה',
    'Asia/Katmandu'  =>  '(UTC +05:45 ) קטמנדו',
    'Asia/Dhaka'  =>  '(UTC +06:00) דאקה',
    'Asia/Almaty'  =>  '(UTC +06:00) Almaty',
    'Asia/Yekaterinburg'  =>  '(UTC +06:00) יקטרינבורג',
    'Asia/Rangoon'  =>  '(UTC +06:30) יאנגון ( ראנגון )',
    'Asia/Novosibirsk'  =>  '(UTC +07:00) נובוסיבירסק',
    'Asia/Bangkok'  =>  '(UTC +07:00) בנגקוק , גקרטה',
    'Asia/Brunei'  =>  '(UTC +08:00) בייגינג , צונגצינג , הונג קונג, אורומצי',
    'Asia/Krasnoyarsk'  =>  '(UTC +08:00) קרסנויארסק',
    'Asia/Ulaanbaatar'  =>  '(UTC +08:00) אולאן באטאר',
    'Asia/Kuala_Lumpur'  =>  '(UTC +08:00) קואלה לומפור , סינגפור',
    'Asia/Taipei'  =>  '(UTC +08:00) טייפה',
    'Australia/Perth'  =>  '(UTC +08:00) פרת',
    'Asia/Irkutsk'  =>  '(UTC +09:00) אירקוצק',
    'Asia/Seoul'  =>  '(UTC +09:00) סיאול',
    'Asia/Tokyo'  =>  '(UTC +09:00) טוקיו',
    'Australia/Darwin'  =>  '(UTC +09:30) דרווין',
    'Australia/Adelaide'  =>  '(UTC +09:30) אדלייד',
    'Australia/Canberra'  =>  '(UTC +10:00) קנברה, מלבורן, סידני',
    'Australia/Brisbane'  =>  '(UTC +10:00) בריסביין',
    'Australia/Hobart'  =>  '(UTC +10:00) הובארט',
    'Asia/Vladivostok'  =>  '(UTC +10:00) וולדיווסטוק',
    'Pacific/Guam'  =>  '(UTC +10:00) גואם, פורט מורסבי',
    'Asia/Yakutsk'  =>  '(UTC +10:00) יקוטסק',
    'Pacific/Fiji'  =>  '(UTC +12:00) פיגי',
    'Asia/Kamchatka'  =>  '(UTC +12:00) קמצטקה',
    'Pacific/Auckland'  =>  '(UTC +12:00) אוקלנד',
    'Asia/Magadan'  =>  '(UTC +12:00) מגדן',
    'Pacific/Tongatapu'  =>  '(UTC +13:00) Nukualofa',

	'Summary'=>'תקציר',
	'Detail'=>'פרט',
	'LBL_USER_LIST_DETAILS'=>'פרטים',
	
	'LBL_OLD_PASSWORD'=>'סיסמא ישנה',
	'LBL_CHANGE_PASSWORD'=>'שינוי סיסמא',
	'LBL_NEW_PASSWORD'=>'סיסמא חדשה',
	'LBL_CONFIRM_PASSWORD'=>'אשר סיסמא',
	
	//Login strings
	'LBL_TO_CRM'=>'כניסה ל-CRM vtiger',
	'LBL_INVALID_USER_OR_PASSWORD'=>'שם משתמש או סיסמא לא חוקיים.',
	'LBL_INVALID_USER_OR_EMAIL'=>'שם משתמש לא חוקי או כתובת דואר אלקטרוני .',
	'LBL_EMAIL_SEND'=>'שלחתי לך דוא"ל לאיפוס הסיסמה שלך.',
	'ForgotPassword'=>'שכחת את הסיסמה',
	'LBL_CONNECT_WITH_US'=>'צור קשר עם ארה"ב',
	'LBL_GET_MORE'=>'קבל יותר מvtiger',
	
	'LBL_TRANSFER_RECORDS_TO_USER'=>'להעביר את הרשומות למשתמש',
	'LBL_USER_TO_BE_DELETED'=>'משתמששנמחק',
);

$jsשפהStrings = array(
	'JS_ENTER_OLD_PASSWORD'=>'אנא הכנס את הסיסמה הישנה שלך.',
	'JS_ENTER_NEW_PASSWORD'=>'אנא הכנס את הסיסמה החדשה שלך.',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'נא להזין את אישור הסיסמה שלך.',
	'JS_REENTER_PASSWORDS'=>'Please re-enter passwords.  The \"new password\" and \"confirm password\" values do not match.',
	'JS_INVALID_PASSWORD'=>'עליך לצייןאת שם המשתמש וסיסמא תקפים.',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'שינוי סיסמא המשתמש נכשל עבור',
	'JS_PASSWORD_CHANGE_FAILED_2'=>' נכשל. הסיסמה החדשה חייבת להיות מוגדרת .',
	'JS_PASSWORD_INCORRECT_OLD'=>'סיסמא ישנה שגויה שצוינה. להזין מחדש את פרטי סיסמא.',
);