<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/

$languageStrings = array(
		'Status'                       => 'מצב',
		'Due date' => 'תאריך יעד',
		'Related to'=>'קשור ל',
		'Service Requests'=>'קריאות שירות',
	'APPTITLE'                     => 'מערכת ניהול לקוחות', 
	'POWEREDBY'                    => 'Powered by vtiger CRM ', 
	'LBL_READ_LICENSE'             => 'רשיון ', 
	'LBL_PRIVACY_POLICY'           => 'Privacy Policy ', 
	'LBL_SELECT_ALL'               => 'בחר הכל ', 
	'LBL_SELECT_TO_LOAD_LIST'      => 'בחר רשימה לטעינה ', // TODO: Review
	'LBL_CREATING_NEW'             => 'צור חדש ', 
	'LBL_EDITING'                  => 'עריכה ', 
	'LBL_SAVE'                     => 'שמור ', 
	'LBL_CANCEL'                   => 'בטל ', 
	'LBL_BACK'                     => 'חזור ', 
	'LBL_IMPORT'                   => 'ייבוא ', 
	'LBL_EXPORT'                   => 'ייצוא ', 
	'LBL_FIND_DUPLICATES'          => 'מצא כפילויות ', 
	'LBL_MORE'                     => 'עוד ', 
	'LBL_ACTIONS'                  => 'פעולות ', 
	'LBL_ADD'                      => 'הוסף ', 
	'LBL_EDIT'                     => 'ערוך ', 
	'LBL_DELETE'                   => 'מחק ', 
	'LBL_SETTINGS'                 => 'הגדרות ', 
	'LBL_ADD_COMMENT'              => 'הוסף הערה ', 
	'LBL_EDIT_FIELDS'              => 'ערוך שדות ', 
	'LBL_EDIT_WORKFLOWS'           => 'ערוך זרימת עבודה ', 
	'LBL_EDIT_PICKLIST_VALUEזזS'     => 'Edit Picklist Values ',
	'LBL_EDIT_MAILSCANNER'         => 'המר דוא"ל ', 
	'LBL_RECORD_DELETE'            => 'הרשומה שאתה מנסה לראות נמחקה.', 
	'LBL_RECORD_NOT_FOUND'         => 'הרשומה שאתה מנסה לגשת אליה לא נמצאה', 
	'LBL_SELECT'                   => 'בחר ', 
	'LBL_CLEAR'                    => 'נקה ', 
	'LBL_YES'                      => 'כן ', 
	'LBL_NO'                       => 'לא ', 
	'LBL_SHOW_COMPLETE_DETAILS'    => 'פרטי מלאים ', // TODO: Review
	'LBL_MASS_EDITING'             => 'עריכת אצווה ', 
	'LBL_DESELECT_ALL_RECORDS'     => 'הסר בחירה מהכל ', 
	'LBL_QUICK_CREATE'             => 'צור מקוצר ', 
	'LBL_SEND_EMAIL'               => 'שלח דוא"ל ', 
	'LBL_ALL_EMAILS'               => 'כל חשבונות הדוא"ל ', 
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'בחר באחת מהאפשרויות למטה',
	'LBL_GO_TO_FULL_FORM'          => 'גש לטופס מלא ', 
	'LBL_SEND_SMS'                 => 'שלח SMS ', 
	'LBL_FOUND'                    => 'נמצא ', 
	'LBL_CLICK_ADD'                => 'לחץ הוסף ', 
	'LBL_ADD_MORE_FIELDS'          => 'הוסף שדות נוספים ', 
	'LBL_ADD_NOTE'                 => 'הוסף פתק ', 
	'LBL_CREATE_NEW'               => 'צור חדש ', 
	'LBL_ADD_EVENT'                => 'הוסף אירוע ', 
	'LBL_ADD_TASK'				   => 'הוסף משימה ',
	'LBL_MARKETING_AND_SALES'      => 'שיווק ומכירות ', 
	'LBL_TOOLS_HEADER'             => 'כלים ', 
	'LBL_SUPPORT'                  => 'תמיכה ', 
	'LBL_INVENTORY'                => 'מלאי ', 
	'LBL_ANALYTICS'                => 'ניתוח נתונים ', 
	'LBL_HOME'                     => 'ראשי ', 
	'LBL_LAST_VIEWED_RECORDS'      => 'רשומות אחרונות שנצפו ', 
	'LBL_DASHBOARD'                => 'לוח בקרה ', 
	'LBL_USER_SETTINGS'            => 'הגדרות משתמש ', 
	'LBL_MY_PREFERENCES'           => 'ההגדרות שלי ', 
	'LBL_SIGN_OUT'                 => 'התנתק ', 
	'LBL_HELP'                     => 'עזרה ', 
	'LBL_DOCUMENTATION'            => 'תיעוד ', // TODO: Review
	'LBL_VIDEO_TUTORIAL'           => 'מדריך וידאו ', // TODO: Review
	'LBL_FEEDBACK'                 => 'משוב ',
	'LBL_CHAT_SUPPORT'			   => 'תמיכה בצ\'ט',
	'LBL_CRM_SETTINGS'             => 'הגדרות מערכת ', 
	'LBL_ON_DEMAND_ADMIN'          => 'הוסף \ מחק משתמשים ', // TODO: Review
	'LBL_ANNOUNCEMENT'             => 'הודעה ', 
	'LBL_CALENDAR'                 => 'לוח שנה ', 
	'LBL_POST'                     => 'פוסט ', 
	'LBL_GUIDER'                   => 'Guider ', // TODO: Review
	'LBL_DISPLAY_TYPE'             => 'Display Type ', // TODO: Review
	'LBL_DISPLAY_WIDETYPE'         => 'Wide ', // TODO: Review
	'LBL_DISPLAY_MEDIUMTYPE'       => 'Medium ', // TODO: Review
	'LBL_DISPLAY_NARROWTYPE'       => 'Narrow ', // TODO: Review
	'LBL_TAG_THIS_RECORD'          => 'Tag this Record ', // TODO: Review
	'LBL_PAGE'                     => 'Page ', // TODO: Review
	'LBL_LISTVIEW_PAGE_JUMP'       => 'Page Jump ', // TODO: Review
	'LBL_USER'                     => 'משתמש ', 
	'LBL_GROUP'                    => 'קבוצה ', 
	'Last Modified By'             => 'עודכן לאחרונה על ידי ', 
	'Created Time'                 => 'נוצר ב  ', 
	'Modified Time'                => 'עודכן ב ', 
	'Description'                  => 'תיאור ', 
	'Assigned To'                  => 'הוקצה ל ', 
	'LBL_LOADING'                  => 'טוען... ', 
	'LBL_LOADING_WIDGET'           => 'טוען וידג\'ט ', 
	'LBL_LOADING_LISTVIEW_CONTENTS' => 'טוען, נא להמתין ', 
	'LBL_UPDATES'                  => 'עדכונים ', 
	'LBL_SHOW_FULL_DETAILS'        => 'הצג פרטים מלאים ', // TODO: Review
	'LBL_SUMMARY_DETAILS'          => 'תקציר פררטים ', 
	'LBL_ADD_NEW_COMMENT'          => 'הוסף הערה חדשה ', 
	'LBL_NO_UPDATES'               => 'אין עדכונים ', 
	'LBL_ACTIVITIES'               => 'פעילויות ', // TODO: Review
	'LBL_NO_PENDING_ACTIVITIES'    => 'אין פעילויות בתהליך ', // TODO: Review
	'LBL_SUMMARY'                  => 'סיכום ', // TODO: Review
	'LBL_DETAILS'                  => 'פרטים ', // TODO: Review
	'LBL_SEARCH_FOR'               => 'חפש ', 
	'LBL_IN'                       => 'ב ', 
	'LBL_TYPE_SEARCH'              => 'הקלד לחפש ', 
	'LBL_SEARCH_BUTTON'            => 'כפתור חיפוש ', 
	'LBL_ADVANCE_SEARCH'           => 'מתקדים ', 
	'LBL_LOADING_PLEASE_WAIT'      => 'טוען, אנא המתן ', 
	'LBL_USERS'                    => 'משתמשים ', 
	'LBL_GROUPS'                   => 'קבוצות ', 
	'LBL_FULL_FORM'                => 'טופס מלא ', 
	'LBL_SIMPLE_FORM'              => 'טופס פשוט ', 
	'LBL_ADD_YOUR_COMMENT_HERE'    => 'הוסף הערתך כאן... ', 
	'LBL_REPLY'                    => 'השב ', 
	'LBL_VIEW_THREAD'              => 'צפה בהודעה ', 
	'LBL_NO_COMMENTS'              => 'אין הערות ', 
	'LBL_REPLIES'                  => 'תשובות ', 
	'Accounts'                     => 'ארגונים ', 
	'Assets'                       => 'נכסים ', 
	'Calendar'                     => 'לוח שנה ', 
	'Campaigns'                    => 'קמפיינים ', 
	'Contacts'                     => 'אנשי קשר ', 
	'Documents'                    => 'מסמכים ', 
	'Leads'                        => 'לידים ', 
	'ModComments'                  => 'הערות ', 
	'Potentials'                   => 'הזדמנויות ', 
	'PriceBooks'                   => 'ספרי מחירים ', 
	'Products'                     => 'מוצרים ', 
	'Project'                      => 'פרוייקטים ', 
	'ProjectMilestone'             => 'יעדי פרוייקט ', 
	'ProjectTask'                  => 'משימות פרוייקט ', 
	'ServiceContracts'             => 'אנשי קשר לשירות ', 
	'Services'                     => 'שירותים ', 
	'Vendors'                      => 'יצרנים ', 
	'Rss'                          => 'RSS ', 
	'Quotes'                       => 'הצעות מחיר ', 
	'PurchaseOrder'                => 'הזמנת עבודה ', 
	'SalesOrder'                   => 'הזמנת מכירה ', 
	'Invoice'                      => 'חשבונית ', 
	'MailManager'                  => 'מנהל דואר ', // TODO: Review
	'Activities'				   => 'פעילויות ',
    'LBL_ADD_RECORD'               => 'הוסף רשומה ', 
	'LBL_RECENTLY_MODIFIED'        => 'עודכנו לאחרונה ', 
	'LBL_RECORDS_LIST'             => 'רשומות ', 
	'LBL_RECORD_SUMMARY'           => 'תקציר ', 
	'LBL_ACCESS_DENIED_FOR'        => 'הגישה נדחתה עבור ', 
	'LBL_GO_BACK'                  => 'חזור ', 
	'LBL_NO_DATA_AVAILABLE'        => 'אין מידע זמין ', 
	'LBL_GLOBAL_SEARCH'            => 'הקלד מילת חיפוש ולחץ ENTER', 
	'LBL_ALL_RECORDS'              => 'כל הרשומות ', // TODO: Review
	'LBL_NO_RECORDS_FOUND'         => 'לא נמצאו רשומות ', // TODO: Review
	'LBL_AND'                      => 'ו ', 
	'LBL_OR'                       => 'או ', 
	'LBL_NONE'                     => '--אין-- ', 
	'LBL_APPROVE'                  => 'אשר ', 
	'LBL_DENY'                     => 'דחה ', 
	'LBL_EQUALS'                   => 'שווה ', 
	'LBL_NOT_EQUAL_TO'             => 'לא שווה ', 
	'LBL_STARTS_WITH'              => 'מתחיל ב ', 
	'LBL_ENDS_WITH'                => 'מסתיים ב ', 
	'LBL_CONTAINS'                 => 'מכיל ', 
	'LBL_DOES_NOT_CONTAIN'         => 'אינו מכיל ', 
	'LBL_LESS_THAN'                => 'פחות מ ', 
	'LBL_GREATER_THAN'             => 'יותר מ ', 
	'LBL_LESS_THAN_OR_EQUAL'       => 'קטן או שווה ', 
	'LBL_GREATER_OR_EQUAL'         => 'גדול או שווה' , 
	'LBL_BEFORE'                   => 'לפני ', 
	'LBL_AFTER'                    => 'אחרי ', 
	'LBL_BETWEEN'                  => 'בין ', 
    'LBL_IS_NOT_EMPTY'             => 'iאינו ריק ',
	'LBL_SEARCH'                   => 'חפש ', 
	'LBL_SEARCH_IN'                => 'חפש ב ', 
	'LBL_ADD_CONDITION'            => 'הוסף תנאי ', 
	'LBL_ADD_GROUP'                => 'הוסף קבוצה ', 
	'LBL_FILTER_CONDITIONS'        => 'סנן תנאים ', 
	'LBL_ALL_CONDITIONS'           => 'כל התנאים ', 
	'LBL_ALL_CONDITIONS_DESC'      => 'כל התנאים סופקו ', 
	'LBL_ANY_CONDITIONS'           => 'כל תנאי ', 
	'LBL_ANY_CONDITIONS_DESC'      => 'לפחות אחד מהתנאים', 
	'LBL_SELECT_FIELD'             => 'בחר שדה ', 
	'LBL_SELECT_MODULE'            => 'בחר מודול ', 
	'LBL_CREATE_NEW_FILTER'        => 'צור מסנן חדש ', 
	'All'                          => 'הכל ', 
	'Others'                       => 'אחרים ', 
	'Pending'                      => 'ממתין ', 
	'Public'                       => 'ציבורי ', 
	'LBL_SAVE_FILTER'              => 'שמור מסנן ', 
	'LBL_SAVE_MODIFY_FILTER'       => 'שמור\עדכן מסנן ', 
	'LBL_SEARCH_RESULTS'           => 'תוצאות חיפוש ', 
	'LBL_SAVE_AS_FILTER'           => 'שמור כמסנן ', 
	'LBL_NOT_ACCESSIBLE'           => 'לא נגיש ', 
	'LBL_ITEM_DETAILS'             => 'פרטי פריט ', 
	'LBL_CURRENCY'                 => 'מטבע ', 
	'LBL_TAX_MODE'                 => 'מצב מס ', 
	'LBL_INDIVIDUAL'               => 'יחיד ', 
	'LBL_TOOLS'                    => 'כלים ', 
	'LBL_ITEM_NAME'                => 'שם פריט ', 
	'LBL_QTY_IN_STOCK'             => 'כמות במלאי ', 
	'LBL_QTY'                      => 'כמות ', 
	'LBL_LIST_PRICE'               => 'מחיר ללקוח ', 
	'LBL_TOTAL'                    => 'סה"כ ', 
	'LBL_NET_PRICE'                => 'מחיר נטו ', 
	'LBL_DISCOUNT'                 => 'הנחה ', 
	'LBL_TOTAL_AFTER_DISCOUNT'     => 'סה"כ לאחר הנחה ', 
	'LBL_TAX'                      => 'מס ', 
	'LBL_ADD_PRODUCT'              => 'הוסף מוצר ', 
	'LBL_ADD_SERVICE'              => 'הוסף שירות ', 
	'LBL_ITEMS_TOTAL'              => 'סה"כ למוצר ', // TODO: Review
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'עלות משלוח ', 
	'LBL_PRE_TAX_TOTAL'            => 'סה"כ לפני מס ', // TODO: Review
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'מסים למשלוח', 
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Set S&H Taxes for ', 
	'LBL_ADJUSTMENT'               => 'תיקון ', 
	'LBL_DEDUCT'                   => 'ניקוי מס ', 
	'LBL_GRAND_TOTAL'              => 'סה"כ כללי ', 
	'LBL_ZERO_DISCOUNT'            => 'אפס הנחה ', 
	'LBL_OF_PRICE'                 => 'ממחיר ', 
	'LBL_DIRECT_PRICE_REDUCTION'   => 'Direct Price Reduction ', 
	'LBL_SET_DISCOUNT_FOR'         => 'Set Discount For ', 
	'LBL_STOCK_NOT_ENOUGH'         => 'Not Enough Stock ', 
	'LBL_MAX_QTY_SELECT'           => 'Maxmimum value is ', 
	'LBL_DRAG'                     => 'Drag ', 
	'LBL_TOTAL_TAX_AMOUNT'         => 'Total Tax Amount ', 
	'LBL_DIRECT_AMOUNT_DISCOUNT'   => 'Direct Amount Discount ', 
	'LBL_FINAL_DISCOUNT_AMOUNT'    => 'Final Discount Amount ', 
	'LBL_MORE_CURRENCIES'          => 'More Currencies ', 
	'LBL_SET_TAX_FOR'              => 'Set Tax for ', // TODO: Review
	'LBL_GROUP_TAX'                => 'Group Tax ', // TODO: Review
	'LBL_BILLING_ADDRESS_FROM'     => 'Copy Invoice Address from ', // TODO: Review
	'LBL_SHIPPING_ADDRESS_FROM'    => 'Copy Delivery Address from ', // TODO: Review
	'LBL_COPY_SHIPPING_ADDRESS'    => 'Delivery Address ', // TODO: Review
	'LBL_COPY_BILLING_ADDRESS'     => 'Invoice Address ', // TODO: Review
	'LBL_CREATE'                   => 'צור ', 
	'LBL_GENERATE'                 => 'ייצר ', 
	'LBL_DUPLICATE'                => 'שכפל ', 
	'LBL_ADD_WIDGET'               => 'Add Widget ', 
	'LBL_COMMENTS'                 => 'הערות ', 
	'LBL_REFRESH'                  => 'רענן ', 
	'LBL_CLOSE'                    => 'סגור ', 
	'LBL_ALL'                      => 'הכל ', 
	'LBL_UPDATED'                  => 'עודכן ', 
	'LBL_FROM'                     => 'מ ', 
	'LBL_TO'                       => 'ל ',
    'LBL_to'                       => 'ל ',
	'LBL_ON'                       => 'על ', 
	'LBL_OF'                       => 'מתוך ', 
	'LBL_BY'                       => 'על ידי  ', 
	'LBL_ADDED'                    => 'נוסף ל', 
	'LBL_FOR'                      => 'עבור ', 
	'LBL_CREATED'                  => 'נוצר ', 
	'LBL_DELETED'                  => 'נמחק ', 
	'LBL_RESTORED'                 => 'שוחזר ', 
	'LBL_COMMENTED'                => 'הוער ', 
	'LBL_REMOVED'                  => 'הוסר ', 
	'LBL_REMOVE'                   => 'הסר ', 
	'LBL_AT'                       => 'ב ', 
	'LBL_MINE'                     => 'שלי ', 
	'History'                      => 'היסטוריה ', 
	'Upcoming Tasks'               => 'משימות ממתמינות ', 
	'LBL_YEAR'                     => 'שנה &nbsp;', 
	'LBL_YEARS'                    => 'שנים &nbsp;', 
	'LBL_MONTH'                    => 'חודש &nbsp;', 
	'LBL_MONTHS'                   => 'חודשים &nbsp;', 
	'LBL_DAY'                      => 'יום&nbsp;', 
	'LBL_DAYS'                     => 'ימים &nbsp;', 
	'LBL_HOUR'                     => 'שעה &nbsp;', 
	'LBL_HOURS'                    => 'שעות &nbsp;', 
	'LBL_MINUTE'                   => 'דקה &nbsp;', 
	'LBL_MINUTES'                  => 'דקות &nbsp;', 
	'LBL_SECOND'                   => 'שנייה &nbsp;', 
	'LBL_SECONDS'                  => 'שניות &nbsp;', 
	'LBL_JUSTNOW'                  => 'כרגע &nbsp;', 
	'LBL_CUSTOM_INFORMATION'       => 'מידע ייחודי ', 
	'LBL_NO_RECENT_UPDATES'        => 'אין עדכונים ', 
	'LBL_NO_DATA'                  => 'אין מידע ', 
	'LBL_PERMISSION_DENIED'        => 'אין הרשאה ', 
	'LBL_HANDLER_NOT_FOUND'        => 'Handler not found ', 
	'LBL_FILTER'                   => 'מסנן ', 
	'LBL_DUE'                      => 'לטיפול עד ', 
	'LBL_COMPLETED'                => 'הסתיים ', 
	'LBL_AGO'                      => '    ', 
	'LBL_CHANGED'                  => 'שונה ', 
	'Single_Users'                 => 'משתמש ', 
	'LBL_MATCHED_THIS_CRITERIA'    => 'מתאים לקריטריונים ', 
	'LBL_NO_SCHEDULED_ACTIVITIES'  => 'אין פעילויות מתוכננות ', 
	'LBL_NO_OVERDUE_ACTIVITIES'    => 'אין פעילויות בעיכוב ', 
	'LBL_NO_UPDATES_OR_COMMENTS'   => 'אין עדכונים או הערות ', 
	'LBL_MINI_LIST'                => 'Mini List ', // TODO: Review
	'Mini List'                    => 'Mini List ', // TODO: Review
	'LBL_RESULT_FOR_THE_TAG'       => 'תוצאות עבור טאג ', // TODO: Review
	'LBL_VIEW_NAME'                => 'View Name ', 
	'LBL_CREATE_VIEW'              => 'Creating New View ', 
	'LBL_BASIC_DETAILS'            => 'פרטים ראשוניים ', 
	'LBL_CHOOSE_COLUMNS'           => 'Choose Columns and Order ', 
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Max 7 ', 
	'LBL_FILTER_ON_DATE'           => 'סנן לפי תאריך ', 
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Choose filter Conditions ', 
	'LBL_SET_AS_DEFAULT'           => 'קבע ברירת מחדל ', 
	'LBL_LIST_IN_METRICS'          => 'List in Metrics ', 
	'LBL_SET_AS_PUBLIC'            => 'Set as Public ', 
	'LBL_ADD_MORE_COLUMNS'         => 'Add more Columns ', 
	'LBL_CUSTOM'                   => 'Custom ', 
	'LBL_PREVIOUS_FY'              => 'Previous FY ', 
	'LBL_CURRENT_FY'               => 'Current FY ', 
	'LBL_NEXT_FY'                  => 'Next FY ', 
	'LBL_PREVIOUS_FQ'              => 'Previous FQ ', 
	'LBL_CURRENT_FQ'               => 'Current FQ ', 
	'LBL_NEXT_FQ'                  => 'Next FQ ', 
	'LBL_YESTERDAY'                => 'אתמול ', 
	'LBL_TODAY'                    => 'היום ', 
	'LBL_TOMORROW'                 => 'מחר ', 
	'LBL_LAST_WEEK'                => 'שבוע הבא ', 
	'LBL_CURRENT_WEEK'             => 'השבוע ', 
	'LBL_NEXT_WEEK'                => 'שבוע הבא ', 
	'LBL_LAST_MONTH'               => 'חודש הבא ', 
	'LBL_CURRENT_MONTH'            => 'החודש ', 
	'LBL_NEXT_MONTH'               => 'חודש הבא ', 
	'LBL_LAST_7_DAYS'              => '7 ימים אחרונים ', 
	'LBL_LAST_30_DAYS'             => '30 ימים אחרונים ', 
	'LBL_LAST_60_DAYS'             => '60 ימים אחרונים ', 
	'LBL_LAST_90_DAYS'             => '90 ימים אחרונים ', 
	'LBL_LAST_120_DAYS'            => '120 ימים אחרונים ', 
	'LBL_NEXT_30_DAYS'             => '30 הימים הבאים ', 
	'LBL_NEXT_60_DAYS'             => '60 הימים הבאים ', 
	'LBL_NEXT_90_DAYS'             => '90 הימים הבאים ', 
	'LBL_NEXT_120_DAYS'            => '120 הימים הבאים ', 
	'LBL_OWNER'                    => 'בעלים ', 
	'LBL_CREATED_ON'               => 'נוצר ב ', 
	'LBL_MODIFIED_ON'              => 'שונה ב ', 
	'LBL_BEFORE_EVENT'             => 'לפני האירוע ', 
	'Upcoming Activities'          => 'פעילויות הבאות ', 
	'Overdue Activities'           => 'פעילויות בעיכוב ', 
	'Funnel'                       => 'משפך ', 
	'Potentials by Stage'          => 'הזדמנויות על פי מצב ', 
	'Pipelined Amount'             => 'Sales Pipeline ', 
	'Total Revenue'                => 'הכנסה כללית ', 
	'Top Potentials'               => 'הזדמנויות בולטות ', 
	'Forecast'                     => 'תחזית ', 
	'Leads Created'                => 'לידים נוצרו ', 
	'Leads by Status'              => 'לידים על פי סטטוס ', 
	'Leads by Source'              => 'לידים על פי מקור ', 
	'Leads by Industry'            => 'לידים לפי תעשייה ', 
	'Tickets by Status'            => 'קריאות שירות לפי סטטוס ', // TODO: Review
	'Open Tickets'                 => 'קריאות שירות פתוחות ', // TODO: Review
	'LBL_EXPORT_ALL_DATA'          => 'ייצא את כל המידע', 
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'Eייצא את המידע שבדף זה', 
	'LBL_EXPORT_RECORDS'           => 'Export Record Types ', 
	'LBL_NO_RECORD_SELECTED'       => 'No record selected. ', 
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Cannot remove default widget', 
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'Filter already exists ', 
	'LBL_ADD_MANAGE_MODULES'       => 'Add / Manage Modules ', 
	'Account Name'                 => 'שם הארגון ', 
	'Add Comment'                  => 'הוסף הערה ', 
	'Adjustment'                   => 'תיקון ', 
	'Annual Revenue'               => 'הכנסה שנתית ', 
	'Apparel'                      => 'ביגוד ', 
	'Banking'                      => 'בנקים ', 
	'Billing Address'              => 'כתובת חיוב ', 
	'Billing City'                 => 'עיר חיוב ', 
	'Billing Code'                 => 'מיקוד חיוב ', 
	'Billing Country'              => 'ארץ חיוב ', 
	'Billing Po Box'               => 'ת.ד. חיוב ', 
	'Billing State'                => 'ארץ חיוב ', 
	'Biotechnology'                => 'ביוטכנולוגיה ', 
	'FedEx'                        => 'FedEx ', 
	'UPS'                          => 'UPS ', 
	'USPS'                         => 'USPS ', 
	'DHL'                          => 'DHL ', 
	'BlueDart'                     => 'BlueDart ', 
	'Carrier'                      => 'Carrier ', 
	'Category'                     => 'קטגוריה ', 
	'Chemicals'                    => 'כימיכלים ', 
	'City'                         => 'עיר ', 
	'Cold Call'                    => 'שיחה קרה ', 
	'Existing Customer'            => 'לקוח קיים ', 
	'Self Generated'               => 'ייצור עצמי ', 
	'Employee'                     => 'עובד ', 
	'Partner'                      => 'שותף עסקי ', 
	'Public Relations'             => 'יחצי ציבור ', 
	'Direct Mail'                  => 'דואר ישיר ', 
	'Conference'                   => 'ועידה ', 
	'Trade Show'                   => 'תערוכה ', 
	'Web Site'                     => 'אתר אינטרנט ', 
	'Word of mouth'                => 'מפה לאוזן ', 
	'Other'                        => 'אחר ', 
	'--None--'                     => '--ללא-- ', 
	'Acquired'                     => 'נרכש ', 
	'Active'                       => 'פעיל ', 
	'Market Failed'                => 'כשלון שיווק ', 
	'Project Cancelled'            => 'פרוייקט בוטל ', 
	'Shutdown'                     => 'כיבוי ', 
	'Communications'               => 'תקשורת ', 
	'Construction'                 => 'בנייה ', 
	'Consulting'                   => 'ייעוץ ', 
	'Education'                    => 'חינוך ', 
	'Electronics'                  => 'אלקטרוניקה ', 
	'Energy'                       => 'אנרגיה ', 
	'Engineering'                  => 'הנדסה ', 
	'Entertainment'                => 'בידור ', 
	'Environmental'                => 'סביבה ', 
	'Finance'                      => 'פיננסים ', 
	'Food & Beverage'              => 'אוכל ומשקאות ', 
	'Government'                   => 'ממשלתי ', 
	'Healthcare'                   => 'בריאות ', 
	'Hospitality'                  => 'אירוח ', 
	'Insurance'                    => 'ביטוח ', 
	'Machinery'                    => 'מיכון ', 
	'Manufacturing'                => 'ייצור ', 
	'Media'                        => 'מדיה ', 
	'Not For Profit'               => 'ללא מטרות רווח ', 
	'Recreation'                   => 'פנאי ', 
	'Retail'                       => 'קמעונאות ', 
	'Shipping'                     => 'שילוח ', 
	'Technology'                   => 'טכנולוגיה ', 
	'Telecommunications'           => 'תקשורת ', 
	'Transportation'               => 'תחבורה ', 
	'Utilities'                    => 'שירותים ', 
	'Contact Name'                 => 'שם ', 
	'Conversion Rate'              => 'יחס המרה ', 
	'Shipping Address'             => 'כתובת למשלוח ', 
	'Shipping City'                => 'עיר למשלוח ', 
	'Shipping State'               => 'ארץ למשלוח ', 
	'Shipping Code'                => 'מיקוד למשלוח ', 
	'Shipping Country'             => 'ארץ למשלוח ', 
	'Shipping Po Box'              => 'ת.ד. למשלוח ', 
	'Country'                      => 'ארץ ', 
	'Created'                      => 'נוצר ', 
	'Approved'                     => 'אושר ', 
	'Delivered'                    => 'נשלח ', 
	'Cancelled'                    => 'בוטל ', 
	'Currency'                     => 'מטבע ', 
	'LBL_BASE_CURRENCY'            => 'מטבע בסיס ', 
	'Discount Percent'             => 'אחוזי הנחה ', 
	'Discount Amount'              => 'סכום הנחה ', 
	'Item Discount Amount'         => 'סכום הנחה למוצר ', 
	'Item Discount Percent'        => 'אחוז הנחה למוצר ', 
	'Due Date'                     => 'תאריך יעד ', 
	'Due Date & Time'              => 'תאריך ושעת יעדe ', 
	'Email'                        => 'דוא"ל ', 
	'Secondary Email'              => 'דוא"ל משני ', 
	'Other Email'                  => 'דוא"ל אחר ', 
	'Email Opt Out'                => 'Email Opt Out ', 
    'Is Converted From Lead'       => 'הומר מליד ',
	'Expected Close Date'          => 'תאריך סגירה צפוי ', 
	'Fax'                          => 'פקס ', 
	'Last Name'                    => 'שם משפחה ', 
	'First Name'                   => 'שם פרטי ', 
	'High'                         => 'גבוה ', 
	'Low'                          => 'נמוך ', 
	'In Progress'                  => 'בתהליך ', 
	'Subject'                      => 'נושא ', 
	'Terms & Conditions'           => 'תנאים ', 
	'Item Name'                    => 'שם פריט ', 
	'Quantity'                     => 'כמות ', 
	'List Price'                   => 'מחיר ננקוב ', 
	'Item Comment'                 => 'Item Comment ', 
	'Tax1'                         => 'Tax1 ', 
	'Tax2'                         => 'Tax2 ', 
	'Tax3'                         => 'Tax3 ', 
	'Excise Duty'                  => 'Excise Duty ', 
	'Total'                        => 'Total ', 
	'Sub Total'                    => 'Sub Total ', 
	'Tax Type'                     => 'Tax Type ', 
	'S&H Amount'                   => 'S&H Amount ', 
	'Status'                       => 'Status ', 
	'Vendor Name'                  => 'יצרן ', 
	'LBL_ADDRESS_INFORMATION'      => 'כתובת ', 
	'LBL_DESCRIPTION_INFORMATION'  => 'תיאור ', 
	'LBL_TERMS_INFORMATION'        => 'תנאי שימוש ', 
	'LBL_PRICING_INFORMATION'      => 'מידע תמחור ', 
	'LBL_RELATED_PRODUCTS'         => 'פרטי מוצר ', 
	'LBL_REMINDER_INFORMATION'     => 'פרטי תזכורת ', 
	'LBL_FOLDER_SAVED'             => 'תיקייה נשמרה ', 
	'LBL_FOLDER_EXISTS'            => 'תיקייה קיימת ', 
	'LBL_FOLDER_DELETED'           => 'תיקייה נמחקה ', 
	'Lead Source'                  => 'מקור הליד ', 
	'Mobile'                       => 'נייד ', 
	'Notify Owner'                 => 'הודע לבעלים ', 
	'Other Phone'                  => 'טלפון אחר ', 
	'Phone'                        => 'טלפון ', 
	'State'                        => 'מחוז ', 
	'Po Box'                       => 'ת.ד. ', 
	'Postal Code'                  => 'מיקוד ', 
	'Potential Name'               => 'שם הזדמנות ', 
	'Priority'                     => 'עדיפות ', 
	'Product Name'                 => 'שם המוצר ', 
	'Rating'                       => 'דירוג ', 
	'Related To'                   => 'קשור אל ', 
	'Type'                         => 'סוג ', 
	'Reviewed'                     => 'נסקר ', 
	'Salutation'                   => 'תואר  ', 
	'Street'                       => 'רחוב ', 
	'Support Start Date'           => 'Support Start Date ', 
	'Support Expiry Date'          => 'Support Expiry Date ', 
	'Sales Start Date'             => 'Sales Start Date ', 
	'Sales End Date'               => 'Sales End Date ', 
	'Open Ticktes'                 => 'קריאות שירות פתוחות ', // TODO: Review
	'LBL_SELECT_STATUS'            => 'בחר סטטוס ',
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'מערכת CRM RCT ', 
	'SINGLE_Accounts'              => 'ארגון ', // TODO: Review
	'SINGLE_Contacts'              => 'איש קשר ', // TODO: Review
	'LBL_Sun'                      => 'ראשון ', // TODO: Review
	'LBL_Mon'                      => 'שני ', // TODO: Review
	'LBL_Tue'                      => 'שלישי ', // TODO: Review
	'LBL_Wed'                      => 'רביעי ', // TODO: Review
	'LBL_Thu'                      => 'חמישי ', // TODO: Review
	'LBL_Fri'                      => 'שישי ', // TODO: Review
	'LBL_Sat'                      => 'שבת ', // TODO: Review
	'LBL_Jan'                      => 'ינואר ', // TODO: Review
	'LBL_Feb'                      => 'פברואר ', // TODO: Review
	'LBL_Mar'                      => 'מרץ ', // TODO: Review
	'LBL_Apr'                      => 'אפריל ', // TODO: Review
	'LBL_May'                      => 'מאי ', // TODO: Review
	'LBL_Jun'                      => 'יוני ', // TODO: Review
	'LBL_Jul'                      => 'יולי ', // TODO: Review
	'LBL_Aug'                      => 'אוגוסט ', // TODO: Review
	'LBL_Sep'                      => 'ספטמבר ', // TODO: Review
	'LBL_Oct'                      => 'אוקטובר ', // TODO: Review
	'LBL_Nov'                      => 'נובמבר ', // TODO: Review
	'LBL_Dec'                      => 'דצמבר ', // TODO: Review
	'LBL_CALENDAR_SETTINGS'        => 'הגדרות לוח שנה ', // TODO: Review
        'Reminder Interval'            => 'תכיפות התראות ',
	'HelpDesk'                     => 'קריאות שירות ', // TODO: Review
	'LBL_TAG_CLOUD'                => 'ענן תאגים ', // TODO: Review
	'LBL_NO_RECORDS'               => 'אין רשומות ', // TODO: Review
	'LBL_NO_RELATED'               => 'אין רשומות קשורות ', // TODO: Review
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Only the first 100 results of all modules are shown below. For module specific results, please select respective module and search', // TODO: Review
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Only the first 100 results are shown below. Please use Advanced Search if you are not satisfied with the result', // TODO: Review
	'LBL ACTION'                   => 'פעולה ', // TODO: Review
	'LBL_NOTE'                     => 'פתק ', // TODO: Review
	'LBL_SELECT_OPTION'            => 'בחר אפשרות ', // TODO: Review
	'LBL_TOOLTIP'                  => 'Tooltip Management ', // TODO: Review
	'LBL_MODULE_SEQUENCE_NUMBERING' => 'Module Sequence Numbering ', // TODO: Review
	'LBL_CUSTOM_FIELD_MAPPING'     => 'Custom Field Mapping ', // TODO: Review
	'LBL_WEBFORMS'                 => 'WebForms ', // TODO: Review
	'SINGLE_Emails'                => 'Email ', 
	'Emails'                       => 'Emails ', // TODO: Review
	'LBL_SELECT_EMAIL_IDS'         => 'Select Email Addresses ', // TODO: Review
	'LBL_SUBJECT'                  => 'Subject ', // TODO: Review
	'LBL_ATTACHMENT'               => 'Attachment ', // TODO: Review
	'LBL_BROWSE_CRM'               => 'Browse CRM ', // TODO: Review
	'LBL_SEND'                     => 'Send ', // TODO: Review
	'LBL_SAVE_AS_DRAFT'            => 'Save as Draft ', // TODO: Review
	'LBL_GO_TO_PREVIEW'            => 'Go to Preview ', // TODO: Review
	'LBL_SELECT_EMAIL_TEMPLATE'    => 'Select Email Template ', // TODO: Review
	'LBL_COMPOSE_EMAIL'            => 'Compose Email ', // TODO: Review
	'LBL_CC'                       => 'Cc ', // TODO: Review
	'LBL_BCC'                      => 'Bcc ', // TODO: Review
	'LBL_ADD_CC'                   => 'Add Cc ', // TODO: Review
	'LBL_ADD_BCC'                  => 'Add Bcc ', // TODO: Review
	'LBL_MAX_UPLOAD_SIZE'          => 'Maximum upload size is ', // TODO: Review
	'LBL_EXCEEDED'                 => 'Exceeded ', // TODO: Review
	'LBL_MERGE'                    => 'אחד',
	//Translations used for Export to Pdf
	'Valid Date' => 'תאריך תקין',
	'Phone: ' => 'טלפון: ',
	'Issued Date' => 'זמן הוספה',
	'Shipping & Handling Charges' => 'Shipping & Handling Charges',
	'Shipping & Handling Tax:' => 'Shipping & Handling Tax:',
	'Discount'=>'Discount',
	'Net Total' => 'Net Total',
	'Product Code'=>'Product Code',
	'Customer Name'=>'Customer Name',
	'Price'=>'Price',
	'Tax:' => 'Tax:',
	'Contact Name' => 'Contact Name',
	'Grand Total:' => 'Grand Total:',
	'Fax: ' => 'Fax: ',
	'Website: ' => 'Website: ',
	'Tax' => 'Tax',
        #'LBL_ALPHABETS' => 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z',
		'LBL_ALPHABETS' => 'א,ב,ג,ד,ה,ו,ז,ח,ט,י,כ,ל,מ,נ,ס,ע,פ,צ,ק,ר,ש,ת',
	
	//Realted tab strings
	'Service Contracts' => 'Service Contracts',
	'Projects' => 'פרוייקטים',
	'Sales Order' => 'הזמנת עבודה',
	'Purchase Order' => 'הזמנת רכש',
	'List and Campaigns' => 'List and Campaigns',
	'Project Tasks' => 'משימות פרוייקט',
	'Project Milestones' => 'יעדי פרוייקט',
	
	'Labels Editor' => 'Label Editor',
	'LBL_IGNORE_EMPTY_VALUES' =>'Ignore empty values',
	
	//Related tabs of Products
	'Product Bundles' => 'Product Bundles',
	'Parent Product' => 'Parent Product',
	
	'LBL_MANAGE_USERS' => 'Manage Users',
	'LBL_TRANSFER_OWNERSHIP' => 'Transfer Ownership',
	'LBL_SELECT_RELATED_MODULES' => 'Select Related Modules',
	
	'LBL_CUSTOMIZE_MAIN_MENU' => 'Customise Main Menu', //TODO REVIEW
		'Status' => 'סטטוס',
		'description'=>'תיאור',
	//For Print Templates
    'Print Templates' => 'תבניות הדפסה',
    'Print' => 'הדפס / ייצא ל-PDF',
	//Comments Field Labels for Workflow
	'Comment' => 'הערה',
	'Last Comment' => 'הערה אחרונה',
	'Last 5 Comments' => '5 הערות אחרונות',
	'All Comments' => 'כל ההערות',
		'Created By'=>'נוצר על ידי',
		'Project Task Name'=>'שם משימת פרוייקט',
		'Progress'=>'התקדמות',
		'ProjectMilestone'=>'אבני דרך',
		'Documents'=>'מסמכים',
		'ProjectTask'=>'משימת פרוייקט'
);
$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Please configure your outgoing server settings from the Settings page', 
	'JS_SMS_SERVER_CONFIGURATION'  => 'Please configure your SMS Notifier from the SMS Notifier Settings page', 
	'JS_PLEASE_SELECT_ONE_RECORD'  => 'Please select at least one record', 
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Please enter a valid email address', 
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'contains illegal characters ', 
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'phone number length exceeded limit', 
	'JS_ACCEPT_POSITIVE_NUMBER'    => 'accepts only positive values', 
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'value should be greater than zero', 
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'Number should be less than 32', 
	'JS_PLEASE_ENTER_VALID_DATE'   => 'Please enter a valid date ', 
	'JS_PLEASE_ENTER_VALID_TIME'   => 'Please enter a valid time ', 
	'JS_INVALID_PAGE_NUMBER'       => 'Invalid Page Number ', 
	'INVALID_NUMBER_OF'            => 'Invalid number ', 
	'INVALID_NUMBER'               => 'Invalid number ', 
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Are you sure that you want to delete?', 
	'OVERWRITE_EXISTING_MSG1'      => 'Overwrite the existing address with the selected address?', 
	'OVERWRITE_EXISTING_MSG2'      => 'Address Details ', 
	'SINGLE_Accounts'              => 'Organisation ', 
	'SINGLE_Contacts'              => 'Contact ', 
	'LBL_DELETE_CONFIRMATION'      => 'Are you sure you want to Delete?', 
	'LBL_MASS_DELETE_CONFIRMATION' => 'Are you sure you want to delete the selected Records?', 
	'JS_LBL_SAVE'                  => 'Save ', 
	'JS_LBL_CANCEL'                => 'Cancel ', 
	'SHOULD_BE_LESS_THAN_TODAY'    => 'Must occur before today ', 
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Please select atleast one option', 
	'JS_SELECT_MODULE'             => 'Please Select Module ', 
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Please select at least one mandatory field', 
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'Please enter integer value ', 
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Please enter decimal value ', 
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'should be less than current date', 
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'should be greater than current date', 
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'should be greater than or equal to', 
	'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'should be less than or equal to', 
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'Percentage value should be less than 100', 
	'JS_ACCEPT_ONLY_NUMBER'        => 'Accepts only numbers ', 
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'This File has already been selected', 
	'JS_MAX_FILE_UPLOAD_EXCEEDS'   => 'max file upload exceeds ', 
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'This Document has already been attached', 
	'JS_FAILED_TO_SAVE'            => 'Failed to save changes on server', 
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'Import File cannot be Empty ', 
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Select at least one field for merge criteria', 
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'Map Name cannot be empty ', 
	'JS_MAP_NAME_ALREADY_EXISTS'   => 'Map Name already exists ', 
	'JS_SELECT_FILE_EXTENSION'     => 'Please select a file with the following extension:', 
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'Upload file size should be less than', 
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Uploaded file size exceeds ', 
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Please split the file into smaller files and import again.', 
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Field mapped more than once ', 
	'JS_MAP_MANDATORY_FIELDS'      => 'Please map mandatory fields ', 
	'JS_PLEASE_ENTER_SOME_VALUE'   => 'Please enter some value to search', 
	'JS_YOU_CAN_SELECT_ONLY'       => 'You can select only ', 
	'JS_ITEMS'                     => 'items ', 
	'JS_LBL_PERMISSION'            => 'Permissions ', 
	'JS_CHECK_FILE_INTEGRITY'      => 'Check File Integrity ', 
	'JS_DUPLICATE_RECORD'          => 'Duplicate Record ', 
	'JS_IS_ENABLED'                => 'is enabled ', 
	'JS_IS_DISABLED'               => 'is disabled ', 
	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Please enter some text for comment', 
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'Comment value cannot be empty', 
	'JS_REQUIRED_FIELD'            => '* This field is required ', 
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Cannot remove Default Widget', 
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'No create permissions or not enabled for quick create', 
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'Image Deleted Successfully ', 
	'LBL_IMAGE_NOT_DELETED'        => 'Image Not Deleted ', 
	'LBL_YES'                      => 'Yes ', 
	'LBL_NO'                       => 'No ', 
	'AM'                           => 'AM ', 
	'PM'                           => 'PM ', 
	'JS_ERROR'                     => 'Error ', // TODO: Review
	'JS_INFORMATION'               => 'Information ', // TODO: Review
	'JS_DO_NOT_HAVE_AN_EMAIL_ID'   => 'does not have an email address', // TODO: Review
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'None of the field values are changed in Mass Edit', // TODO: Review
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Please select an Organisation to copy address', // TODO: Review
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Please select a Contact to copy address', // TODO: Review
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Organisation does not contain address to copy', // TODO: Review
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Contact does not contain address to copy', // TODO: Review
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Please enter Primary email address to enable portal user', // TODO: Review
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Primary email field does not exist to enable portal user', // TODO: Review
	'JS_PLEASE_ENTER_A_TAG'        => 'Please enter a tag ', // TODO: Review
	'JS_TAG_NAME_ALREADY_EXIST'    => 'Tag name already exist ', // TODO: Review
	'JS_MAX_TAG_LENGTH_EXCEEDS'    => 'Tag length exceeds max size ', // TODO: Review
	'JS_NO_VIEW_PERMISSION_AFTER_SAVE' => 'You will not have permissions to view this record after save. Would you like to continue?', // TODO: Review
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'No Records Related to this Filter', // TODO: Review
	'JS_START_DATE_TIME'           => 'Start Date & Time ', // TODO: Review
	'JS_END_DATE_TIME'             => 'End Date & Time ', // TODO: Review
	'JS_POSTPONE'                  => 'Postpone ', // TODO: Review
	'JS_MESSAGE'                   => 'Message ', // TODO: Review
	'JS_MASS_EDIT_LIMIT'	       => 'Mass Edit operation can be done on 500 or less records at a time',
	'JS_SUCCESSFULLY_PINNED'       => 'Shortcut added successfully ', // TODO: Review
	'JS_SUCCESSFULLY_UNPINNED'     => 'Shortcut removed successfully', // TODO: Review
	'JS_SHORTCUT_ALREADY_ADDED'    => 'This shortcut is already added', // TODO: Review
	'JS_MODULE_ENABLED'            => 'Module Enabled ', // TODO: Review
	'JS_MODULE_DISABLED'           => 'Module Disabled ', // TODO: Review
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'Frequency of any cron job configured should not be less than', // TODO: Review
	'JS_MINUTES'                   => 'mins ', // TODO: Review
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'Item renamed successfully ', // TODO: Review
	'JS_ITEM_ADDED_SUCCESSFULLY'   => 'Item added successfully ', // TODO: Review
	'JS_NO_ITEM_SELECTED'          => 'No item selected ', // TODO: Review
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'More than one item selected ', // TODO: Review
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'Items deleted successfully ', // TODO: Review
	'JS_DUPLIACATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicate entries found for the value', // TODO: Review
	
	//User Password
	'JS_PASSWORD_INCORRECT_OLD'=>'Incorrect old password specified. Re-enter password information.',
	'JS_PASSWORD_CHANGED_SUCCESSFULLY' => 'Password changed successfully.',
	'JS_REENTER_PASSWORDS'=>'Please re-enter passwords.  The "new password" and "confirm password" values do not match.',
	'JS_RECORDS_TRANSFERRED_SUCCESSFULLY' => 'Records ownership transferred successfully.',
	'JS_USER_EXISTS' => 'User already exists',//TODO Review
	'JS_REENTER_PASSWORDS' => 'Renter Passwords',//TODO Review
    
        // Specific starts - For PBXManager
	'JS_PBX_CALL_FROM' => 'שיחה מאת',
	'JS_PBX_INCOMING_CALL' => 'שיחה נכנסת',
	'JS_PBX_OUTGOING_SUCCESS'=>'Pick up the extension receiver to dial the number',
	'JS_PBX_OUTGOING_FAILURE'=>'שיחה נכשלה',
	'JS_PBX_FILL_ALL_FIELDS'=>'יש למשלא את כל השדות',
	// ends
        
        //No Tax exist 
        'JS_LBL_NO_TAXES'=>'אין מסים', 
);